### ISSUE TITLE
Documentar configuração dos Bancos

### ISSUE THREAD

**Issue by fccoelho** [fccoelho/AlertaDengueCaptura#2]
A instalação e configuração dos bancos para uso precisa ser documentada. No caso do PostgreSQL é bem complicado pois exige a criação de tabelas usuário e direitos de acesso.

Idealmente toda a configuração do postgres deveria ser feita em um arquivo SQL a ser executado após a instalação.

**Comment by ogcruz** [comment]
Oi Flavio, concordo, mas também pode criar e depois fazer um DUMP em SQL
que tudo vai estra la, incluindo a criação das tabelas, direitos para os
usuários e claro os dados se for o caso. E depois com esse arquivo com
certeza pode-se replicar o banco !



Em 9 de maio de 2015 11:16, Flávio Codeço Coelho <notifications@github.com>
escreveu:

**Comment by fccoelho** [comment]
Ok,

depois de terminar a implementação, vou fazer este dump, e salvar o sql,
sem os inserts em um script de configuração no repositório.


2015-05-09 11:31 GMT-03:00 ogcruz <notifications@github.com>:

> Oi Flavio, concordo, mas também pode criar e depois fazer um DUMP em SQL
> que tudo vai estra la, incluindo a criação das tabelas, direitos para os
> usuários e claro os dados se for o caso. E depois com esse arquivo com
> certeza pode-se replicar o banco !
>
>
>
> Em 9 de maio de 2015 11:16, Flávio Codeço Coelho <notifications@github.com
> >
> escreveu:
>
> > A instalação e configuração dos bancos para uso precisa ser documentada.
> > No caso do PostgreSQL é bem complicado pois exige a criação de tabelas
> > usuário e direitos de acesso.
> >
> > Idealmente toda a configuração do postgres deveria ser feita em um
> arquivo
> > SQL a ser executado após a instalação.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/fccoelho/AlertaDengueCaptura/issues/2>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fccoelho/AlertaDengueCaptura/issues/2#issuecomment-100496991>
> .
>



-- 
Flávio Codeço Coelho
================
+55(21) 3799-5551
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil

**Comment by fccoelho** [comment]
Feito
