### ISSUE TITLE
Tratamento de daldos faltantes

### ISSUE THREAD

**Issue by marfcg** [fccoelho/AlertaDengueCaptura#3]
O sistema deve ser capaz de lidar com falta de dados ou erro na captura. 
Devemos ter uma estrutura que possa reconhecer a "posição/janela temporal" faltante e lidar de acordo.
Sugestão para dados climáticos:
"Buraco simples" (não há apenas o ultimo dado, ou há erro em te, mas há dados em te-1 e te+1): interpolação, quando possível, adotando a escala temporal adequada. 
- Se o buraco for na escala horária,  interpolar com os dados da série temporal daquele dia.
- Se o buraco for um dia inteiro, ou uma parcela suficientemente grande do día (definir este intervalo limite), interpolar as variáveis de interesse na escala diária. Isto é,  pegar a série temporal de temperatura mínima de cada dia e fazer a interpolação nesta escala, por exemplo.
- Semana inteira faltando, ou intervalo suficientemente grande (a definir): repetir dado da semana anterior. Ou fazer interpolação com os dados agregados em escala semanal? Como iremos guardar o dado semanal usado nos relatórios,  isso também seria possível. 

Embora a sugestão tenha sido feita para dados climáticos, esta estrutura pode ser adaptada para os demais dados.
Importante: o módulo responsável deve reportar o erro e medida adotada, que devem ser registrados no log de execução.

**Comment by marfcg** [comment]
Na verdade, talvez seja melhor mover essa issue para o AlertaDengueAnalise, não?

**Comment by fccoelho** [comment]
acho que sim.

2015-05-09 16:43 GMT-03:00 Marcelo F C Gomes <notifications@github.com>:

> Na verdade, talvez seja melhor mover essa issue para o
> AlertaDengueAnalise, não?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fccoelho/AlertaDengueCaptura/issues/3#issuecomment-100536390>
> .
>



-- 
Flávio Codeço Coelho
================
+55(21) 3799-5551
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil

**Comment by fccoelho** [comment]
@marfcg , não existe um mecanismo de migração de issue. Logo o procedimento que sugiro é etiquetar este issue como inválido e fechá-lo (o que acabo de fazer) depois você seleciona este issue dentre os fechados e copia e cola o conteúdo em uma nova issue no repo de análise
