### ISSUE TITLE
Automatizar captura de dados

### ISSUE THREAD

**Issue by fccoelho** [fccoelho/AlertaDengueCaptura#4]
@israelst, neste repositório existe o início de uma aplicação celery para automatizar a captura de dados para o projeto. Atualmente, estamos usando scripts isolados no repositório [AlertaDengueAnalise](https://github.com/fccoelho/AlertaDengueAnalise). É uma boa oportunidade para você se familiarizar com o Celery, se já não te for familiar. Qualquer dúvida pergunte ao nosso *celery master:* @flavioamieiro .

O código deste repo tem que rodar diariamente no servidor de dados. No módulo de tasks já existe uma pronta para captura dos dados climáticos do CEMADEN, falta portar os scripts de captura do [weather underground](https://github.com/fccoelho/AlertaDengueAnalise/blob/master/GeraAlerta/fun/clima.py) e dos [tweets](https://github.com/fccoelho/AlertaDengueAnalise/blob/master/GeraAlerta/fun/pega_tweets.py) . Estes scripts devem virar tasks do módulo 
[tasks.py](https://github.com/fccoelho/AlertaDengueCaptura/blob/master/crawlclima/tasks.py)

**Comment by israelst** [comment]
Deixa comigo!

**Comment by fccoelho** [comment]
@israelst, já coloquei os novos scripts (cron) de captura de tweets e chuva para rodar no servidor.
precisamos que você elabore um script simples para ser executado via CRON de maneira a habilitarmos a captura regular dos dados do WU.
Naturalmente, antes disso temos que ter o código de inserção no banco e a lista de estações adicionada ao repositório
